catalog/urls.py
from django.urls import path
from . import views



app_name = 'catalog'


urlpatterns = [
    path('', views.index, name = 'index'),
    path('books/', views.BookListView.as_view(), name = 'books'),
    path('book/<int:pk>/',views.BookDetailView.as_view(), name = 'book-detail'),
    path('authors/', views.AuthorListView.as_view(), name = 'authors'),
    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name = 'author-detail'),
    path('mybooks/', views.LoanedBookByUserListView.as_view(), name = 'my-borrowed'),
]
  
  
urlpatterns += []

locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
      
]



urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

catalog/models.py
import uuid
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date




class Genre (models.Model):
    name = models.CharField(max_length=200, help_text='Enter a book genre(e.g. Science Fiction)')

   #Metadata
    class Meta :
        ordering = ['-name']
   
    def __str__(self):
        return self.name


class Book (models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete = models.SET_NULL, null = True)
    summary = models.TextField(max_length = 1000, help_text = 'Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length = 13, unique = True, help_text = '13 Character <a href = "https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text = 'Select a genre for this book')
    
   
   #Methods
    def get_absolute_url(self):
        return reverse('catalog:book-detail', args=[str(self.id)])
    
    def display_genre(self):
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'

    def __str__(self):
        return self.title
    
    
class BookInstance(models.Model):
    id = models.UUIDField(primary_key = True, default = uuid.uuid4, help_text = 'Unique ID for this particular book across the whole library')
    book = models.ForeignKey('Book', on_delete = models.RESTRICT, null = True)
    imprint = models.CharField(max_length = 200)
    due_back = models.DateField(null = True, blank = True)
    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'), 
    )
    status = models.CharField(max_length = 1, choices = LOAN_STATUS, blank = True, default = 'm', help_text = 'Book availability')
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null = True, blank = True)
    
    class Meta:
        ordering = ['due_back']
        permissions = (
            ('can_mark_returned', 'Set book as returned'),  
        )
        
        
    def __str__(self):
        return f'{self.id} ({self.book.title})'
    
    @property
    def is_overdue(self):
        return bool(self.due_back and date.today() > self.due_back)
    
    
class Author (models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null = True, blank = True)
    date_of_death = models.DateField('Died', null = True, blank = True)
   
   #metadata
    class Meta:
        ordering = ['last_name', 'first_name']

      
   #Methods
    def get_absolute_url(self):
        return reverse('catalog:author-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.last_name} {self.first_name}'
    

catalog/views.py
from django.shortcuts import render
from . models import Book, Author, BookInstance, Genre
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required


def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact = 'a').count()
    num_authors = Author.objects.count()
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1
    context = {
        'num_books':num_books,
        'num_instances':num_instances,
        'num_instances_available':num_instances_available,
        'num_authors':num_authors,
        'num_visits':num_visits
    }
    return render(request, 'catalog/index.html', context)
    
    
class BookListView(generic.ListView):
    model = Book
    paginate_by = 5
    
    
class BookDetailView(generic.DetailView):   
    model = Book
    

class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 10
    
    
class AuthorDetailView(generic.DetailView):
    model = Author

class LoanedBookByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10
    
    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')
    

catalog/templates/catalog/author_detail.html
{% extends 'catalog/base.html' %}
{% block body %}
  <h1 class="title is-1">About <em>{{author.first_name}} {{author.last_name}}</em></h1>
  <p><strong>Full name:</strong> {{author.first_name}} {{author.last_name}}</p>
  <p><strong>Date of Birth:</strong>  {{author.date_of_birth}}</p>
  <p><strong>Died: </strong>{{author.date_of_death}} </p>
{% endblock body %}

catalog/templates/catalog/author_list.html
{% extends 'catalog/base.html' %}
{% block body %}
<h1 class="title is-1">All Authors</h1>
<ul>
    {% for author in author_list %}
        <li><a href="{{author.get_absolute_url}}">{{author.last_name}}</a></li>
    {% endfor %}
</ul>
  
{% endblock body %}

catalog/templates/catalog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bulma.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/debug.cs' %}">

    {% block title %}
    <title>Local Library</title>

    {% endblock title %}
</head>
<body>
    {% block sidebar %}
    <section class="columns">
      <section class="column is-4">
        <p class = 'menu-label is-size-5'>Library Information</p>
        <ul class="menu-list">
          <li><a href="{% url 'catalog:index' %}">Home</a></li>
          <li><a href="{% url 'catalog:books' %}">All books</a></li>
          <li><a href="{% url 'catalog:authors' %}">All authors</a></li>
        </ul>

          <p class="menu-label is-size-5">User Information</p>
          <ul class="menu-list">
            {% if user.is_authenticated %}
              <li><a href="">Welcome <em><strong>{{user.username}}!</strong></em></a></li>
              <li><a href="{% url 'catalog:my-borrowed' %}">My books</a></li>
              <li><a href="{% url 'logout' %}?next={{request.path}}">Logout</a></li>
              {% else %}
              <li><a href="{% url 'login' %}?next={{request.path}}">Login</a></li>
          {% endif %}
          </ul>
          
        
      </section>
      <section class="column m-6 is-8" >
        {% block body %}
                  
                </section>
        {% endblock body %}
      </section>
    {% endblock sidebar %}
  </section>
  <section class="columns">
    <section class="column is-offset-4"></section>
    <section class="column is-4">
      {% block pagination %}
    {% if is_paginated %}
       <section class="pagination is-rounded is-centered" style="max-width: 300px; margin-left: 20px">
            {% if page_obj.has_previous %}
                <a  class="pagination-previous" href="{{request.path}}?page={{page_obj.previous_page_number}}"> Previous</a>
            {% endif %}
        Page <span class="pagination-link has-text-success ">{{page_obj.number}}</span> of <span class="pagination-link">{{page_obj.paginator.num_pages}}
        </span>
            {% if page_obj.has_next %}
                <a class="pagination-next has-text-success" href="{{request.path}}?page={{page_obj.next_page_number}}">Next</a>
            {% endif %}
          </section> 
    {% endif %}
  {% endblock pagination %}
    </section>
    <section class="'column is-offset-4"></section>
  </section>

</body>

</html>






catalog/templates/catalog/book_detail.html
{% extends 'catalog/base.html' %}
{% block body %}
    <h1 class="title is-1">Title: {{book.title}}</h1>
<p><strong>Author: </strong><a href="{{book.author.get_absolute_url}}">{{book.author}}</a></p>
<p><strong>Summary: </strong><a href="">{{book.summary}}</a></p>
<p><strong>Language: </strong><a href="">{{book.language}}</a></p>
<p><strong>Genre: </strong><a href="">{{book.genre.all|join:','}}</a></p>
    <h4>Copies</h4>
    {% for copy in book.bookinstance_set.all %}
        <hr class="has-background-primary">
        <p class="{% if copy.status == 'a' %}
                        has-text-success 
                   {% elif  copy.status == 'm'%}
                        has-text-danger
                          {% else %}
                        has-text-warning
                        {% endif %}">
                        {{copy.get_status_display}}
        </p>
        {% if copy.status != 'a' %}
        <p><strong>Due to be returned: </strong>{{copy.due_back}}</p>
        {% endif %}
        <p><strong>Imprint: </strong>{{copy.imprint}}</p>
        <p class=""><strong>ID: </strong>{{copy.id}}</p>
                  
    {% endfor %}
{% endblock body %}

catalog/templates/catalog/book_list.html
{% extends 'catalog/base.html'%}
{% block body %}
    <h1 class="title is-1">Book List</h1>
    {% if book_list %}
    <ul>
        {% for book in book_list %}
        <li><a href='{{book.get_absolute_url}}'>{{book.title}}</a>  ({{book.author}})</li>
        {% endfor %}
    </ul>
    {% else %}
    <p>There are no books in the library.</p>
    {% endif %}
{% endblock body%}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends 'catalog/base.html' %}
{% block body %}
  <h1 class="title is-1">Borrowed books</h1>
  {% if bookinstance_list %}
      <ul>
        {% for bookinst in bookinstance_list %}
            <li class="{% if bookinst.is_overdue %}
                             has-text-danger
                       {% endif %}">
                       <a href="{% url 'catalog:book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a>   ({{bookinst.due_back}})
            </li>
        {% endfor %}
      </ul>
      {% else %}
          <p>There are no borrowed books</p>
  {% endif %}
{% endblock body %}

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}
{% block body %}
  <h1 class="title is-2">Local Library Home</h1>
  <p>Welcome to Local Library, a website developed by <em>Justin Kpakpa</em>!</p>
  <h2 class="subtitle is-4">Dynamic Content</h2>
  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books: </strong> {{num_books}}</li>
    <li><strong>Copies: </strong> {{num_instances}}</li>
    <li><strong>Copies Available: </strong> {{num_instances_available}}</li>
    <li><strong>Authors: </strong> {{num_authors}}</li>
  </ul>
  <p>You have visited this page {{num_visits}} time{{num_visits|pluralize}}</p>
{% endblock body %}
